language: scala
jdk: openjdk8
branches:
    only:
    - master
stages:
- name: test
- name: release
  if: branch = master AND type = push
jobs:
    include:
        - stage: test
          script: sbt clean +test scalafmtCheck
        - stage: release
          script: sbt clean +test scalafmtCheck stage

webhooks:
    urls:
      - https://webhooks.gitter.im/e/dc45091ae49f5b7d97bd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
