language: scala
jdk: oraclejdk8
branches:
    only:
    - master
stages:
    - name: test
    - name: release
    if: branch = master AND type = push
jobs:
    include:
        - stage: test
          script: sbt +test
        - stage: release
          script: sbt stage
