name: pr
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: |
        sbt test scalafmtCheck stage
        mkdir /tmp/foo
        echo "int foo(int a, int b, int c, int d, int e, int f) {}" > /tmp/foo/foo.c
        ./joern-scan --updatedb
        ./joern --src /tmp/foo --run scan
        ./joern-scan /tmp/foo
        ./joern-scan --dump
        cd joern-cli/target/universal/stage
        ./schema-extender/test.sh
