name: release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt scalafmtCheck test stage
      - run: ./tests/scripts-test.sh
      - run: sbt ciReleaseTagNextVersion createDistribution
      - run: sha512sum ./joern-cli.zip > ./joern-cli.zip.sha512
      - uses: actions/upload-artifact@v2
        with:
          name: joern-cli.zip
          path: |
            joern-install.sh
            joern-cli.zip
            joern-cli.zip.sha512
      - name: Export ENV vars
          run:
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             tag_name: ${{ env.LATEST_TAG }}
             release_name: ${{ env.LATEST_TAG }}
             draft: false
             prerelease: false
